/**
 * App — top-level composition. On mount we try to auto-load the bridged
 * atlas.json that ships with the build (generated by `heal-atlas-from-db`
 * from the heal-daily-pages Postgres). If that fetch fails (404 / parse /
 * validation), the SPA falls back to the empty state and the DataLoader
 * overlay lets the user drop their own file.
 *
 * The Canvas (3D scene) sits in the background; UI overlays float above
 * with pointer-events: auto where interactive.
 */
import { useEffect, useState } from 'react';
import AtlasCanvas from './components/AtlasCanvas';
import ControlBar from './components/ControlBar';
import FilterPanel from './components/FilterPanel';
import TablePanel from './components/TablePanel';
import EventCard from './components/EventCard';
import DataLoader from './components/DataLoader';
import TopologyInfo from './components/TopologyInfo';
import InspectPanel from './components/InspectPanel';
import MetricLens from './components/MetricLens';
import { useAtlasStore } from './store';
import { jsonToDataset } from './schema/adapters/json';
import { parseRawBundle } from './schema/raw';

// Served from Vite's `public/` at the site root. If you ever deploy under a
// subpath, swap to `${import.meta.env.BASE_URL}atlas.json` and add a
// `vite-env.d.ts` referencing `vite/client`.
const BUNDLED_ATLAS_URL = '/atlas.json';
const BUNDLED_RAW_URL = '/raw.json';

export default function App() {
  const setDataset = useAtlasStore(s => s.setDataset);
  const setRawBundle = useAtlasStore(s => s.setRawBundle);
  const resetFilters = useAtlasStore(s => s.resetFilters);
  const theme = useAtlasStore(s => s.theme);
  const [topologyOpen, setTopologyOpen] = useState(false);

  const isLight = theme === 'light';
  // Match the canvas's `<color attach="background">` in Scenery so the
  // wrapper doesn't flash a different color before WebGL paints.
  const wrapperBg = isLight ? '#f4f1ea' : '#040711';
  // Vignette: dark fade-in on dark mode (the original look); a faint
  // warm-gray fade on light mode so the scene still feels framed without
  // muddying the paper background.
  const vignette = isLight
    ? 'radial-gradient(ellipse at center, transparent 55%, rgba(100,116,139,0.18) 100%)'
    : 'radial-gradient(ellipse at center, transparent 50%, rgba(4,7,17,0.6) 100%)';
  const hintColor = isLight ? 'text-slate-500' : 'text-slate-600';

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const resp = await fetch(BUNDLED_ATLAS_URL, { cache: 'no-cache' });
        if (!resp.ok) return;  // 404 → keep empty, user drops a file
        const text = await resp.text();
        const dataset = jsonToDataset(text);
        if (cancelled) return;
        setDataset(dataset);
        const allLabels: string[] = [];
        for (const p of dataset.points) {
          if (p.label) allLabels.push(`${p.category}::${p.label}`);
        }
        resetFilters(dataset.categories.map(c => c.id), allLabels);
      } catch {
        // Silent — DataLoader will surface manual-load errors itself.
      }
    })();
    (async () => {
      // Raw bundle is optional — Raw tab simply shows an empty state when
      // it isn't present. Failure here is silent and independent of atlas.
      try {
        const resp = await fetch(BUNDLED_RAW_URL, { cache: 'no-cache' });
        if (!resp.ok) return;
        const text = await resp.text();
        const bundle = parseRawBundle(text);
        if (cancelled) return;
        setRawBundle(bundle);
      } catch {
        // Silent.
      }
    })();
    return () => { cancelled = true; };
  }, [setDataset, setRawBundle, resetFilters]);

  return (
    <div
      className={`w-full h-screen relative overflow-hidden ${isLight ? 'theme-light' : 'theme-dark'}`}
      style={{ background: wrapperBg }}
    >
      <AtlasCanvas />
      <ControlBar onOpenTopology={() => setTopologyOpen(true)} />
      <DataLoader />
      <FilterPanel />
      <TablePanel />
      <EventCard />
      <TopologyInfo open={topologyOpen} onClose={() => setTopologyOpen(false)} />
      <InspectPanel />
      <MetricLens />

      {/* Bottom-center hint */}
      <div className={`absolute bottom-8 left-1/2 -translate-x-1/2 z-10 text-[10px] tracking-[0.32em] ${hintColor} uppercase pointer-events-none font-mono`}>
        Drag to rotate · Scroll to zoom · Click point to inspect · Click your cluster to morph · Hold space to pause orbit
      </div>

      {/* Vignette overlay */}
      <div
        className="absolute inset-0 pointer-events-none z-10"
        style={{ background: vignette }}
      />
    </div>
  );
}
